### ISSUE TITLE
Deterministic generator

### ISSUE THREAD

**Issue by t-bltg** [Gnimuc/ClangCompiler.jl#24]
I wanted to update the generator for llvm `14.0.6` for julia `1.9` in https://github.com/Gnimuc/ClangCompiler.jl/pull/25, however it seems that the generator handles headers in a non-deterministic way. Re-running the generator thus changes the generated signatures every time.

This, probably because julia `Set`s used in `Clang.jl` are un-ordered:
https://github.com/JuliaInterop/Clang.jl/blob/c95896f223b88b74e51ceeee65ad74a8108e9474/src/generator/context.jl#L252-L253

Should we fix this ?

**Comment by Gnimuc** [comment]
Another way to keep the order of headers deterministic is to include all of the headers in https://github.com/Gnimuc/libclangex/blob/master/include/clang-ex/libclangex.h and only pass `libclangex.h` to Clang.jl's generator without using `detect_headers`.

**Comment by t-bltg** [comment]
List all the headers manually ?
That quite a big list to maintain:
```
CXError.h
CXTypes.h
libclangex.h
AST/CXASTConsumer.h
AST/CXASTContext.h
AST/CXDecl.h
AST/CXDeclBase.h
AST/CXDeclCXX.h
AST/CXDeclGroup.h
AST/CXDeclTemplate.h
AST/CXDeclarationName.h
AST/CXExpr.h
AST/CXMangle.h
AST/CXNestedNameSpecifier.h
AST/CXOperationKinds.h
AST/CXTemplateBase.h
AST/CXTemplateName.h
AST/CXType.h
Basic/CXCodeGenOptions.h
Basic/CXDiagnostic.h
Basic/CXDiagnosticIDs.h
Basic/CXDiagnosticOptions.h
Basic/CXExceptionSpecificationType.h
Basic/CXFileEntry.h
Basic/CXFileManager.h
Basic/CXIdentifierTable.h
Basic/CXLambda.h
Basic/CXLangOptions.h
Basic/CXLinkage.h
Basic/CXModule.h
Basic/CXPragmaKinds.h
Basic/CXSourceLocation.h
Basic/CXSourceManager.h
Basic/CXSpecifiers.h
Basic/CXTargetInfo.h
Basic/CXTargetOptions.h
Basic/CXVisibility.h
CodeGen/CXCodeGenABITypes.h
CodeGen/CXCodeGenAction.h
CodeGen/CXModuleBuilder.h
Driver/CXDriver.h
Frontend/CXCompilerInstance.h
Frontend/CXCompilerInvocation.h
Frontend/CXFrontendOptions.h
Frontend/CXTextDiagnosticPrinter.h
Lex/CXHeaderSearch.h
Lex/CXHeaderSearchOptions.h
Lex/CXLexer.h
Lex/CXPreprocessor.h
Lex/CXPreprocessorOptions.h
Lex/CXToken.h
Parse/CXParseAST.h
Parse/CXParser.h
Sema/CXDeclSpec.h
Sema/CXLookup.h
Sema/CXScope.h
Sema/CXSema.h
```

**Comment by Gnimuc** [comment]
Comparing what I've done in libclangex, this is nothing.

**Comment by t-bltg** [comment]
Oh I didn't notice `libclangex.h` belonging to the `libclangex` repository sorry.
Let's update it then, I will make a PR.
